default: &default
  host: localhost
  user: crystal
  password: crystal
  adapter: postgres

development:
  <<: *default
  db: battlesnake_db_dev

test:
  <<: *default
  db: battlesnake_db_test

production:
  <<: *default
  db: battlesnake_db