name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Cache shards
        uses: actions/cache@v2
        with:
          path: ~/.cache/shards
          key: shards-${{ hashFiles('shard.yml') }}
          restore-keys: ${{ runner.os }}-shards-

      - name: Install shards
        run: shards update

      - name: Run tests
        run: make sam test
        env:
          DATABASE_URI: postgresql://root:postgres@localhost:5432/battlesnake_test
