name: Docker build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, revert-19-revert-18-mosquito-integration]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/battlesnake-test
      KEMAL_ENV: test

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Cache shards
        uses: actions/cache@v2
        with:
          path: ~/.cache/shards
          key: shards-${{ hashFiles('shard.yml') }}
          restore-keys: ${{ runner.os }}-shards-

      - name: Install shards
        run: shards update

      - name: Docker Build
        run: docker build -t fdocr/crystal-snake .

      # - name: Docker Push
      #   run: make sam test
